### ISSUE TITLE
Совместимость с латиницей

### ISSUE THREAD

**Issue by AcostArichA** [1RaY-1/rot13-rus#1]
Хорошая задумка. Жаль нельзя с ней сделать конвеер с TR: латиница→кириллица, чтобы обрабатывать смешанный текст.
Смешанный текст  сейчас часто приходится использовать. 
Примерно так:
echo "Секретная запись, secret text" | tr a-zA-Z n-za-mN-ZA-M | python3 rot13.py
У меня получилось только так:
python3 rot13.py -en "`echo "Секретная запись, secret text" | tr a-zA-Z n-za-mN-ZA-M`"
Эрцьрющлк улыфэз, Эй, что вы пишите!
Однако удаляется латинизированный текст.
Из файла, через "< somefile", тоже не работает.

**Comment by 1RaY-1** [comment]
Хорошая идея кстати латиницу добавить. Я не умею пользоваться ```tr```, но решил отдельно добавить Английский алфавит в этот скрипт, добавил ещё пару ```if``` и теперь можно два языка использовать:
```
python3 rot13.py -en "Секретная запись, secret text"
Юсчэсяъмл фмьхюи, frperg grkg
```

Я  вроде как ошибся раньше и сдвинутый алфавит (rot13) на кириллице начинался с не той буквы, но теперь исправил это. Вроде сейчяс всё ок.

**Comment by AcostArichA** [comment]
Спасибо! Это больше, чем я мог ожидать.
Я в ваш файл, для -help,  добавил:
"Шифрование: python3 rot13.py -en "Текст тут"
Расшифровка: python3 rot13.py -de "Ясчюя яая"."
Так поятнее. 
Подкоманда "-en" больше напоминает English, чем encode.  Возможно "-ru" - шифровка и "-ur" - дешифровка, от Russian, было бы интереснее; правда можно и запутаться.

**Comment by 1RaY-1** [comment]
Вам тоже спасибо, всегда рад таким не сложным, но хорошим идеям.

Этот текст для help сейчяс добавлю, тоже хорошая идея.

Вот что насчёт подкоманд, то как по мне лучше "-en" и "-de".
Но вы и сами можете свою кастомную "ru" и "ur" добавить, это не сложно.
Просто в скрипте когда видите ```-en```,  то меняете на ```-ru```, и тоже самое с дешифровкой.

Вот так просто можно поменять подкоманду, заменив это:
```
if sys.argv[1] == "-en" or sys.argv[1] == "--encode": action = "encode"

elif sys.argv[1] == "-de" or sys.argv[1] == "--decode": action = "decode"
```

На это:
```
if sys.argv[1] == "-ru" or sys.argv[1] == "--encode": action = "encode"

elif sys.argv[1] == "-ur" or sys.argv[1] == "--decode": action = "decode"
```
Ну и в help еще надо будет

**Comment by AcostArichA** [comment]
Спасибо, воспользуюсь.

**Comment by 1RaY-1** [comment]
Так как мы в принципе этот вопрос решили, я закрою этот "issue".
